apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: mealie
  name: mealie
  namespace: mealie
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mealie
  template:
    metadata:
      labels:
        app: mealie
    spec:
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: mealie-data
      containers:
      - image: ghcr.io/mealie-recipes/mealie:v3.3.1
        name: mealie
        ports:
          - containerPort: 9000
        volumeMounts:
        - name: data
          mountPath: /app/data 
